package data

// this is a representaion of home feed row
// not yet stored in a db and is dynamically
// generated by the route
type Feed struct {
	Preference
	Type      FeedType  `json:"type"`
	Title     string    `json:"title"`
	Category  *Category `json:"category"`
	Ordering  int       `json:"ordering"`
	FetchPath string    `json:"fetchPath"`
	Order     int       `json:"order,omitempty"`

	Products []*Product `json:"-"`
}

type Preference struct {
	Style      string `json:"style"`
	Gender     string `json:"gender"`
	Pricing    string `json:"pricing"`
	CategoryID int64  `json:"-"`
}

type FeedType string

const (
	FeedTypeFavourite = "favourite"
	FeedTypeRelated   = "related"
	FeedTypeRecommend = "recommend"
	FeedTypeSale      = "sale"
)
